import EmberObject from '@ember/object';

export default EmberObject.extend({
  recordLayout: [
            {
                "outputLayoutFieldsId": 2555322,
                "fieldName": "Cust_Key",
                "fieldLength": 30,
                "startPosition": 1,
                "endPosition": 30,
                "origination": "SOURCE",
                "sortOrder": 1,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555323,
                "fieldName": "Cust_Source_Key",
                "fieldLength": 30,
                "startPosition": 31,
                "endPosition": 60,
                "origination": "SOURCE",
                "sortOrder": 2,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555324,
                "fieldName": "Cust_Field1",
                "fieldLength": 30,
                "startPosition": 61,
                "endPosition": 90,
                "origination": "SOURCE",
                "sortOrder": 3,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555325,
                "fieldName": "Cust_Field2",
                "fieldLength": 30,
                "startPosition": 91,
                "endPosition": 120,
                "origination": "SOURCE",
                "sortOrder": 4,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555326,
                "fieldName": "Cust_Field3",
                "fieldLength": 30,
                "startPosition": 121,
                "endPosition": 150,
                "origination": "SOURCE",
                "sortOrder": 5,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555327,
                "fieldName": "Company_Name",
                "fieldLength": 60,
                "startPosition": 151,
                "endPosition": 210,
                "origination": "SOURCE",
                "sortOrder": 6,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555328,
                "fieldName": "Primary_Addr1",
                "fieldLength": 55,
                "startPosition": 211,
                "endPosition": 265,
                "origination": "SOURCE",
                "sortOrder": 7,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555329,
                "fieldName": "PO_Box",
                "fieldLength": 55,
                "startPosition": 266,
                "endPosition": 320,
                "origination": "SOURCE",
                "sortOrder": 8,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555330,
                "fieldName": "Primary_City",
                "fieldLength": 30,
                "startPosition": 321,
                "endPosition": 350,
                "origination": "SOURCE",
                "sortOrder": 9,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555331,
                "fieldName": "Primary_State",
                "fieldLength": 2,
                "startPosition": 351,
                "endPosition": 352,
                "origination": "SOURCE",
                "sortOrder": 10,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555332,
                "fieldName": "Primary_Zip",
                "fieldLength": 18,
                "startPosition": 353,
                "endPosition": 370,
                "origination": "SOURCE",
                "sortOrder": 11,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555333,
                "fieldName": "Primary_Country",
                "fieldLength": 30,
                "startPosition": 371,
                "endPosition": 400,
                "origination": "SOURCE",
                "sortOrder": 12,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555334,
                "fieldName": "Primary_Phone",
                "fieldLength": 20,
                "startPosition": 401,
                "endPosition": 420,
                "origination": "SOURCE",
                "sortOrder": 13,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555335,
                "fieldName": "SequenceNumber",
                "fieldLength": 9,
                "startPosition": 421,
                "endPosition": 429,
                "origination": "SEQUENCE NUMBER",
                "sortOrder": 14,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 0,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555336,
                "fieldName": "NCOA Move Effective Date",
                "fieldLength": 6,
                "startPosition": 430,
                "endPosition": 435,
                "origination": "US NCOA",
                "sortOrder": 15,
                "customHeaderField": null,
                "acxFieldName": "coaNewMoveEffectiveDateChar",
                "appendFieldsId": 3577,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555337,
                "fieldName": "Filler",
                "fieldLength": 6,
                "startPosition": 436,
                "endPosition": 441,
                "origination": "US NCOA",
                "sortOrder": 16,
                "customHeaderField": null,
                "acxFieldName": "coacLacsConversionDate",
                "appendFieldsId": 3578,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555338,
                "fieldName": "NIXIE A",
                "fieldLength": 1,
                "startPosition": 442,
                "endPosition": 442,
                "origination": "US NCOA",
                "sortOrder": 17,
                "customHeaderField": null,
                "acxFieldName": "coaNixieA",
                "appendFieldsId": 3579,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555339,
                "fieldName": "NIXIE B",
                "fieldLength": 1,
                "startPosition": 443,
                "endPosition": 443,
                "origination": "US NCOA",
                "sortOrder": 18,
                "customHeaderField": null,
                "acxFieldName": "coaNixieB",
                "appendFieldsId": 3580,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555340,
                "fieldName": "NIXIE C",
                "fieldLength": 1,
                "startPosition": 444,
                "endPosition": 444,
                "origination": "US NCOA",
                "sortOrder": 19,
                "customHeaderField": null,
                "acxFieldName": "coaNixieC",
                "appendFieldsId": 3581,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555341,
                "fieldName": "Primary Number",
                "fieldLength": 10,
                "startPosition": 445,
                "endPosition": 454,
                "origination": "US BASIC",
                "sortOrder": 20,
                "customHeaderField": null,
                "acxFieldName": "cleansed_PriNumber",
                "appendFieldsId": 3595,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555342,
                "fieldName": "Pre-Directional",
                "fieldLength": 2,
                "startPosition": 455,
                "endPosition": 456,
                "origination": "US BASIC",
                "sortOrder": 21,
                "customHeaderField": null,
                "acxFieldName": "cleansed_PreDir",
                "appendFieldsId": 3596,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555343,
                "fieldName": "Street Name",
                "fieldLength": 28,
                "startPosition": 457,
                "endPosition": 484,
                "origination": "US BASIC",
                "sortOrder": 22,
                "customHeaderField": null,
                "acxFieldName": "cleansed_PriName",
                "appendFieldsId": 3597,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555344,
                "fieldName": "Street Suffix",
                "fieldLength": 4,
                "startPosition": 485,
                "endPosition": 488,
                "origination": "US BASIC",
                "sortOrder": 23,
                "customHeaderField": null,
                "acxFieldName": "cleansed_Suffix",
                "appendFieldsId": 3598,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555345,
                "fieldName": "Post Directional",
                "fieldLength": 2,
                "startPosition": 489,
                "endPosition": 490,
                "origination": "US BASIC",
                "sortOrder": 24,
                "customHeaderField": null,
                "acxFieldName": "cleansed_PostDir",
                "appendFieldsId": 3599,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555346,
                "fieldName": "Unit Designator",
                "fieldLength": 4,
                "startPosition": 491,
                "endPosition": 494,
                "origination": "US BASIC",
                "sortOrder": 25,
                "customHeaderField": null,
                "acxFieldName": "cleansed_SecUnitDes",
                "appendFieldsId": 3600,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555347,
                "fieldName": "Secondary Number",
                "fieldLength": 8,
                "startPosition": 495,
                "endPosition": 502,
                "origination": "US BASIC",
                "sortOrder": 26,
                "customHeaderField": null,
                "acxFieldName": "cleansed_SecNumber",
                "appendFieldsId": 3601,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555348,
                "fieldName": "City",
                "fieldLength": 28,
                "startPosition": 503,
                "endPosition": 530,
                "origination": "US BASIC",
                "sortOrder": 27,
                "customHeaderField": null,
                "acxFieldName": "pasCityName",
                "appendFieldsId": 3602,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555349,
                "fieldName": "State",
                "fieldLength": 2,
                "startPosition": 531,
                "endPosition": 532,
                "origination": "US BASIC",
                "sortOrder": 28,
                "customHeaderField": null,
                "acxFieldName": "pasStateAbrev",
                "appendFieldsId": 3603,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555350,
                "fieldName": "ZIP Code",
                "fieldLength": 5,
                "startPosition": 533,
                "endPosition": 537,
                "origination": "US BASIC",
                "sortOrder": 29,
                "customHeaderField": null,
                "acxFieldName": "pasZIPCode",
                "appendFieldsId": 3604,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555351,
                "fieldName": "ZIP +4 Code",
                "fieldLength": 4,
                "startPosition": 538,
                "endPosition": 541,
                "origination": "US BASIC",
                "sortOrder": 30,
                "customHeaderField": null,
                "acxFieldName": "pasAddonCode",
                "appendFieldsId": 3605,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555352,
                "fieldName": "Delivery Point Barcode",
                "fieldLength": 3,
                "startPosition": 542,
                "endPosition": 544,
                "origination": "US BASIC",
                "sortOrder": 31,
                "customHeaderField": null,
                "acxFieldName": "pasDelPtCode",
                "appendFieldsId": 3606,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555353,
                "fieldName": "Carrier Route Code",
                "fieldLength": 4,
                "startPosition": 545,
                "endPosition": 548,
                "origination": "US BASIC",
                "sortOrder": 32,
                "customHeaderField": null,
                "acxFieldName": "pasCarrierID",
                "appendFieldsId": 3607,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555354,
                "fieldName": "Line of Travel Code",
                "fieldLength": 5,
                "startPosition": 549,
                "endPosition": 553,
                "origination": "US BASIC",
                "sortOrder": 33,
                "customHeaderField": null,
                "acxFieldName": "pasLotCode",
                "appendFieldsId": 3608,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555355,
                "fieldName": "AA Match Flag",
                "fieldLength": 1,
                "startPosition": 554,
                "endPosition": 554,
                "origination": "US BASIC",
                "sortOrder": 34,
                "customHeaderField": null,
                "acxFieldName": "NEWPASAAFOOTNOTE",
                "appendFieldsId": 3609,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555356,
                "fieldName": "DSF Match Flag",
                "fieldLength": 1,
                "startPosition": 555,
                "endPosition": 555,
                "origination": "US BASIC",
                "sortOrder": 35,
                "customHeaderField": null,
                "acxFieldName": "pasDSFAddressType",
                "appendFieldsId": 3610,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555357,
                "fieldName": "DSF Sort",
                "fieldLength": 1,
                "startPosition": 556,
                "endPosition": 556,
                "origination": "US BASIC",
                "sortOrder": 36,
                "customHeaderField": null,
                "acxFieldName": "pasDSFSort",
                "appendFieldsId": 3611,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555358,
                "fieldName": "Deliverability Indicator",
                "fieldLength": 1,
                "startPosition": 557,
                "endPosition": 557,
                "origination": "US BASIC",
                "sortOrder": 37,
                "customHeaderField": null,
                "acxFieldName": "pasDSFDeliverabilityInd",
                "appendFieldsId": 3612,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555359,
                "fieldName": "DSF Deliverability Type",
                "fieldLength": 1,
                "startPosition": 558,
                "endPosition": 558,
                "origination": "US BASIC",
                "sortOrder": 38,
                "customHeaderField": null,
                "acxFieldName": "pasDSFDelType",
                "appendFieldsId": 3613,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555360,
                "fieldName": "DSF Vacancy Indicator",
                "fieldLength": 1,
                "startPosition": 559,
                "endPosition": 559,
                "origination": "US BASIC",
                "sortOrder": 39,
                "customHeaderField": null,
                "acxFieldName": "pasDSFVacancy",
                "appendFieldsId": 3614,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555361,
                "fieldName": "DSF Seasonal Indicator",
                "fieldLength": 1,
                "startPosition": 560,
                "endPosition": 560,
                "origination": "US BASIC",
                "sortOrder": 40,
                "customHeaderField": null,
                "acxFieldName": "pasDSFSeasonal",
                "appendFieldsId": 3615,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555362,
                "fieldName": "DSF Drop Indicator",
                "fieldLength": 1,
                "startPosition": 561,
                "endPosition": 561,
                "origination": "US BASIC",
                "sortOrder": 41,
                "customHeaderField": null,
                "acxFieldName": "pasDSFDropInd",
                "appendFieldsId": 3616,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555363,
                "fieldName": "Primary Address",
                "fieldLength": 46,
                "startPosition": 562,
                "endPosition": 607,
                "origination": "US NCOA",
                "sortOrder": 42,
                "customHeaderField": null,
                "acxFieldName": "Primary_Address",
                "appendFieldsId": 3582,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555364,
                "fieldName": "Secondary Address",
                "fieldLength": 12,
                "startPosition": 608,
                "endPosition": 619,
                "origination": "US NCOA",
                "sortOrder": 43,
                "customHeaderField": null,
                "acxFieldName": "Secondary_Address",
                "appendFieldsId": 3583,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555365,
                "fieldName": "PriNum Change Indicator",
                "fieldLength": 1,
                "startPosition": 620,
                "endPosition": 620,
                "origination": "US NCOA",
                "sortOrder": 44,
                "customHeaderField": null,
                "acxFieldName": "PriNum_Change_Indicator",
                "appendFieldsId": 3584,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555366,
                "fieldName": "PreDir Change Indicator",
                "fieldLength": 1,
                "startPosition": 621,
                "endPosition": 621,
                "origination": "US NCOA",
                "sortOrder": 45,
                "customHeaderField": null,
                "acxFieldName": "PreDir_Change_Indicator",
                "appendFieldsId": 3585,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555367,
                "fieldName": "PriName Change Indicator",
                "fieldLength": 1,
                "startPosition": 622,
                "endPosition": 622,
                "origination": "US NCOA",
                "sortOrder": 46,
                "customHeaderField": null,
                "acxFieldName": "PriName_Change_Indicator",
                "appendFieldsId": 3586,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555368,
                "fieldName": "Suffix Change Indicator",
                "fieldLength": 1,
                "startPosition": 623,
                "endPosition": 623,
                "origination": "US NCOA",
                "sortOrder": 47,
                "customHeaderField": null,
                "acxFieldName": "Suffix_Change_Indicator",
                "appendFieldsId": 3587,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555369,
                "fieldName": "PostDir Change Indicator",
                "fieldLength": 1,
                "startPosition": 624,
                "endPosition": 624,
                "origination": "US NCOA",
                "sortOrder": 48,
                "customHeaderField": null,
                "acxFieldName": "PostDir_Change_Indicator",
                "appendFieldsId": 3588,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555370,
                "fieldName": "SecUnitDes Change Indicator",
                "fieldLength": 1,
                "startPosition": 625,
                "endPosition": 625,
                "origination": "US NCOA",
                "sortOrder": 49,
                "customHeaderField": null,
                "acxFieldName": "SecUnitDes_Change_Indicator",
                "appendFieldsId": 3589,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555371,
                "fieldName": "SecNum Change Indicator",
                "fieldLength": 1,
                "startPosition": 626,
                "endPosition": 626,
                "origination": "US NCOA",
                "sortOrder": 50,
                "customHeaderField": null,
                "acxFieldName": "SecNum_Change_Indicator",
                "appendFieldsId": 3590,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555372,
                "fieldName": "CityName Change Indicator",
                "fieldLength": 1,
                "startPosition": 627,
                "endPosition": 627,
                "origination": "US NCOA",
                "sortOrder": 51,
                "customHeaderField": null,
                "acxFieldName": "CityName_Change_Indicator",
                "appendFieldsId": 3591,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555373,
                "fieldName": "StateAbrev Change Indicator",
                "fieldLength": 1,
                "startPosition": 628,
                "endPosition": 628,
                "origination": "US NCOA",
                "sortOrder": 52,
                "customHeaderField": null,
                "acxFieldName": "StateAbrev_Change_Indicator",
                "appendFieldsId": 3592,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555374,
                "fieldName": "ZIPCode Change Indicator",
                "fieldLength": 1,
                "startPosition": 629,
                "endPosition": 629,
                "origination": "US NCOA",
                "sortOrder": 53,
                "customHeaderField": null,
                "acxFieldName": "ZIPCode_Change_Indicator",
                "appendFieldsId": 3593,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555375,
                "fieldName": "ZIP4 Change Indicator",
                "fieldLength": 1,
                "startPosition": 630,
                "endPosition": 630,
                "origination": "US NCOA",
                "sortOrder": 54,
                "customHeaderField": null,
                "acxFieldName": "ZIP4_Change_Indicator",
                "appendFieldsId": 3594,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555376,
                "fieldName": "Cleansed Address 1",
                "fieldLength": 40,
                "startPosition": 631,
                "endPosition": 670,
                "origination": "Global Cleansing",
                "sortOrder": 55,
                "customHeaderField": null,
                "acxFieldName": "GC_AddressLine1",
                "appendFieldsId": 3448,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555377,
                "fieldName": "Cleansed Address 2",
                "fieldLength": 40,
                "startPosition": 671,
                "endPosition": 710,
                "origination": "Global Cleansing",
                "sortOrder": 56,
                "customHeaderField": null,
                "acxFieldName": "GC_AddressLine2",
                "appendFieldsId": 3449,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555378,
                "fieldName": "Cleansed Address 3",
                "fieldLength": 40,
                "startPosition": 711,
                "endPosition": 750,
                "origination": "Global Cleansing",
                "sortOrder": 57,
                "customHeaderField": null,
                "acxFieldName": "GC_AddressLine3",
                "appendFieldsId": 3450,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555379,
                "fieldName": "Cleansed Address 4",
                "fieldLength": 40,
                "startPosition": 751,
                "endPosition": 790,
                "origination": "Global Cleansing",
                "sortOrder": 58,
                "customHeaderField": null,
                "acxFieldName": "GC_AddressLine4",
                "appendFieldsId": 3451,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555380,
                "fieldName": "Filler",
                "fieldLength": 40,
                "startPosition": 791,
                "endPosition": 830,
                "origination": "Global Cleansing",
                "sortOrder": 59,
                "customHeaderField": null,
                "acxFieldName": "GC_CityLine",
                "appendFieldsId": 3452,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555381,
                "fieldName": "Cleansed Country Name",
                "fieldLength": 30,
                "startPosition": 831,
                "endPosition": 860,
                "origination": "Global Cleansing",
                "sortOrder": 60,
                "customHeaderField": null,
                "acxFieldName": "GC_CountryName",
                "appendFieldsId": 3453,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555382,
                "fieldName": "Cleansed County/Province",
                "fieldLength": 20,
                "startPosition": 861,
                "endPosition": 880,
                "origination": "Global Cleansing",
                "sortOrder": 61,
                "customHeaderField": null,
                "acxFieldName": "GC_CountyProvince",
                "appendFieldsId": 3454,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555383,
                "fieldName": "Cleansed City",
                "fieldLength": 40,
                "startPosition": 881,
                "endPosition": 920,
                "origination": "Global Cleansing",
                "sortOrder": 62,
                "customHeaderField": null,
                "acxFieldName": "GC_City",
                "appendFieldsId": 3455,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555384,
                "fieldName": "Cleansed State/Province",
                "fieldLength": 3,
                "startPosition": 921,
                "endPosition": 923,
                "origination": "Global Cleansing",
                "sortOrder": 63,
                "customHeaderField": null,
                "acxFieldName": "GC_State",
                "appendFieldsId": 3456,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555385,
                "fieldName": "Cleansed Postal Code",
                "fieldLength": 10,
                "startPosition": 924,
                "endPosition": 933,
                "origination": "Global Cleansing",
                "sortOrder": 64,
                "customHeaderField": null,
                "acxFieldName": "GC_PostalCode",
                "appendFieldsId": 3457,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555386,
                "fieldName": "Cleansed Process Code",
                "fieldLength": 1,
                "startPosition": 934,
                "endPosition": 934,
                "origination": "Global Cleansing",
                "sortOrder": 65,
                "customHeaderField": null,
                "acxFieldName": "GC_ProcessCode",
                "appendFieldsId": 3458,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555387,
                "fieldName": "Profanity Flag",
                "fieldLength": 1,
                "startPosition": 935,
                "endPosition": 935,
                "origination": "Global Cleansing",
                "sortOrder": 66,
                "customHeaderField": null,
                "acxFieldName": "GC_ProfaneWordFlag",
                "appendFieldsId": 14923,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555388,
                "fieldName": "Cleansed Address Status Code",
                "fieldLength": 1,
                "startPosition": 936,
                "endPosition": 936,
                "origination": "Global Cleansing",
                "sortOrder": 67,
                "customHeaderField": null,
                "acxFieldName": "GC_AddressStatusCode",
                "appendFieldsId": 14924,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555389,
                "fieldName": "Highest Level of Address Verification",
                "fieldLength": 1,
                "startPosition": 937,
                "endPosition": 937,
                "origination": "Global Cleansing",
                "sortOrder": 68,
                "customHeaderField": null,
                "acxFieldName": "GC_HighestLevelAddrVerificationFlag",
                "appendFieldsId": 14925,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555390,
                "fieldName": "Cleanse Match Return Code",
                "fieldLength": 1,
                "startPosition": 938,
                "endPosition": 938,
                "origination": "Global Cleansing",
                "sortOrder": 69,
                "customHeaderField": null,
                "acxFieldName": "GC_MatchReturnCode",
                "appendFieldsId": 14926,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555391,
                "fieldName": "Global Deliverability Code",
                "fieldLength": 2,
                "startPosition": 939,
                "endPosition": 940,
                "origination": "Global Cleansing",
                "sortOrder": 70,
                "customHeaderField": null,
                "acxFieldName": "GC_DeliverabilityCode",
                "appendFieldsId": 14927,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555392,
                "fieldName": "Global Deliverability Summary Code",
                "fieldLength": 1,
                "startPosition": 941,
                "endPosition": 941,
                "origination": "Global Cleansing",
                "sortOrder": 71,
                "customHeaderField": null,
                "acxFieldName": "GC_DeliverabilitySummaryCode",
                "appendFieldsId": 14928,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555393,
                "fieldName": "Filler",
                "fieldLength": 2,
                "startPosition": 942,
                "endPosition": 943,
                "origination": "Global Cleansing",
                "sortOrder": 72,
                "customHeaderField": null,
                "acxFieldName": "GC_Filler_1",
                "appendFieldsId": 14929,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555394,
                "fieldName": "Match Code",
                "fieldLength": 1,
                "startPosition": 944,
                "endPosition": 944,
                "origination": "Matching",
                "sortOrder": 73,
                "customHeaderField": null,
                "acxFieldName": "Match_Code",
                "appendFieldsId": 3542,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555395,
                "fieldName": "BEMFAB (Marketability)",
                "fieldLength": 1,
                "startPosition": 945,
                "endPosition": 945,
                "origination": "Matching",
                "sortOrder": 74,
                "customHeaderField": null,
                "acxFieldName": "BEMFAB",
                "appendFieldsId": 3543,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555396,
                "fieldName": "D-U-N-S Number",
                "fieldLength": 9,
                "startPosition": 946,
                "endPosition": 954,
                "origination": "Matching",
                "sortOrder": 75,
                "customHeaderField": null,
                "acxFieldName": "DUNS",
                "appendFieldsId": 3544,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555397,
                "fieldName": "MatchGrade",
                "fieldLength": 7,
                "startPosition": 955,
                "endPosition": 961,
                "origination": "Matching",
                "sortOrder": 76,
                "customHeaderField": null,
                "acxFieldName": "Match_Grade",
                "appendFieldsId": 3545,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555398,
                "fieldName": "Confidence Code",
                "fieldLength": 2,
                "startPosition": 962,
                "endPosition": 963,
                "origination": "Matching",
                "sortOrder": 77,
                "customHeaderField": null,
                "acxFieldName": "Confidence",
                "appendFieldsId": 3546,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555399,
                "fieldName": "Filler",
                "fieldLength": 4,
                "startPosition": 964,
                "endPosition": 967,
                "origination": "Matching",
                "sortOrder": 78,
                "customHeaderField": null,
                "acxFieldName": "Accuracy",
                "appendFieldsId": 3547,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555400,
                "fieldName": "Name Profile Code",
                "fieldLength": 2,
                "startPosition": 968,
                "endPosition": 969,
                "origination": "Matching",
                "sortOrder": 79,
                "customHeaderField": null,
                "acxFieldName": "Name_Profile_Code",
                "appendFieldsId": 3548,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555401,
                "fieldName": "Street Number Profile Code",
                "fieldLength": 2,
                "startPosition": 970,
                "endPosition": 971,
                "origination": "Matching",
                "sortOrder": 80,
                "customHeaderField": null,
                "acxFieldName": "Str_Number_Profile_Code",
                "appendFieldsId": 3549,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555402,
                "fieldName": "Street Name Profile Code",
                "fieldLength": 2,
                "startPosition": 972,
                "endPosition": 973,
                "origination": "Matching",
                "sortOrder": 81,
                "customHeaderField": null,
                "acxFieldName": "Str_Name_Profile_Code",
                "appendFieldsId": 3550,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555403,
                "fieldName": "City Profile Code",
                "fieldLength": 2,
                "startPosition": 974,
                "endPosition": 975,
                "origination": "Matching",
                "sortOrder": 82,
                "customHeaderField": null,
                "acxFieldName": "City_Profile_Code",
                "appendFieldsId": 3551,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555404,
                "fieldName": "State/Province Profile Code",
                "fieldLength": 2,
                "startPosition": 976,
                "endPosition": 977,
                "origination": "Matching",
                "sortOrder": 83,
                "customHeaderField": null,
                "acxFieldName": "St_Prov_Profile_Code",
                "appendFieldsId": 3552,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555405,
                "fieldName": "PO Box Profile Code",
                "fieldLength": 2,
                "startPosition": 978,
                "endPosition": 979,
                "origination": "Matching",
                "sortOrder": 84,
                "customHeaderField": null,
                "acxFieldName": "PO_Box_Profile_Code",
                "appendFieldsId": 3553,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555406,
                "fieldName": "Phone Profile Code",
                "fieldLength": 2,
                "startPosition": 980,
                "endPosition": 981,
                "origination": "Matching",
                "sortOrder": 85,
                "customHeaderField": null,
                "acxFieldName": "Phone_Profile_Code",
                "appendFieldsId": 3554,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555407,
                "fieldName": "Verified D-U-N-S Number",
                "fieldLength": 9,
                "startPosition": 982,
                "endPosition": 990,
                "origination": "Recertification",
                "sortOrder": 86,
                "customHeaderField": null,
                "acxFieldName": "DUNS_RECERT",
                "appendFieldsId": 3540,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555408,
                "fieldName": "Recertification Reason Code",
                "fieldLength": 1,
                "startPosition": 991,
                "endPosition": 991,
                "origination": "Recertification",
                "sortOrder": 87,
                "customHeaderField": null,
                "acxFieldName": "Reason_Code",
                "appendFieldsId": 3541,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555409,
                "fieldName": "D-U-N-S Number",
                "fieldLength": 9,
                "startPosition": 992,
                "endPosition": 1000,
                "origination": "DMI Mail Record",
                "sortOrder": 88,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 5548,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555410,
                "fieldName": "Business Name",
                "fieldLength": 30,
                "startPosition": 1001,
                "endPosition": 1030,
                "origination": "DMI Mail Record",
                "sortOrder": 89,
                "customHeaderField": null,
                "acxFieldName": "BUSINESS_NME_30",
                "appendFieldsId": 5549,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555411,
                "fieldName": "Mailing Address",
                "fieldLength": 25,
                "startPosition": 1031,
                "endPosition": 1055,
                "origination": "DMI Mail Record",
                "sortOrder": 90,
                "customHeaderField": null,
                "acxFieldName": "TELE_ADDRESS_1_25",
                "appendFieldsId": 5550,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555412,
                "fieldName": "Mailing City Name",
                "fieldLength": 13,
                "startPosition": 1056,
                "endPosition": 1068,
                "origination": "DMI Mail Record",
                "sortOrder": 91,
                "customHeaderField": null,
                "acxFieldName": "MAIL_RECORD_MAIL_CITY",
                "appendFieldsId": 5551,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555413,
                "fieldName": "Mailing State Code",
                "fieldLength": 2,
                "startPosition": 1069,
                "endPosition": 1070,
                "origination": "DMI Mail Record",
                "sortOrder": 92,
                "customHeaderField": null,
                "acxFieldName": "OTHER_PRIM_STATE",
                "appendFieldsId": 5552,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555414,
                "fieldName": "Mailing ZIP Code",
                "fieldLength": 5,
                "startPosition": 1071,
                "endPosition": 1075,
                "origination": "DMI Mail Record",
                "sortOrder": 93,
                "customHeaderField": null,
                "acxFieldName": "TELE_ZIP_5",
                "appendFieldsId": 5553,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555415,
                "fieldName": "ZIP+4 Extension",
                "fieldLength": 4,
                "startPosition": 1076,
                "endPosition": 1079,
                "origination": "DMI Mail Record",
                "sortOrder": 94,
                "customHeaderField": null,
                "acxFieldName": "MAIL_ADDR_ZIP4",
                "appendFieldsId": 5554,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555416,
                "fieldName": "Carrier Route Code",
                "fieldLength": 4,
                "startPosition": 1080,
                "endPosition": 1083,
                "origination": "DMI Mail Record",
                "sortOrder": 95,
                "customHeaderField": null,
                "acxFieldName": "CARRIER_RT_CD",
                "appendFieldsId": 5555,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555417,
                "fieldName": "Delivery Point Code",
                "fieldLength": 2,
                "startPosition": 1084,
                "endPosition": 1085,
                "origination": "DMI Mail Record",
                "sortOrder": 96,
                "customHeaderField": null,
                "acxFieldName": "DELIV_POINT_CD",
                "appendFieldsId": 5556,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555418,
                "fieldName": "Filler",
                "fieldLength": 2,
                "startPosition": 1086,
                "endPosition": 1087,
                "origination": "DMI Mail Record",
                "sortOrder": 97,
                "customHeaderField": null,
                "acxFieldName": "PACKAGE_LVL_CD_2",
                "appendFieldsId": 5557,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555419,
                "fieldName": "Chief Executive Officer - First Name",
                "fieldLength": 13,
                "startPosition": 1088,
                "endPosition": 1100,
                "origination": "DMI Mail Record",
                "sortOrder": 98,
                "customHeaderField": null,
                "acxFieldName": "CEO_FIRST_NME",
                "appendFieldsId": 5558,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555420,
                "fieldName": "Chief Executive Officer - Middle Initial",
                "fieldLength": 1,
                "startPosition": 1101,
                "endPosition": 1101,
                "origination": "DMI Mail Record",
                "sortOrder": 99,
                "customHeaderField": null,
                "acxFieldName": "CEO_MIDDLE_NME",
                "appendFieldsId": 5559,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555421,
                "fieldName": "Chief Executive Officer - Last Name",
                "fieldLength": 15,
                "startPosition": 1102,
                "endPosition": 1116,
                "origination": "DMI Mail Record",
                "sortOrder": 100,
                "customHeaderField": null,
                "acxFieldName": "CEO_LAST_NME",
                "appendFieldsId": 5560,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555422,
                "fieldName": "Chief Executive Officer - Suffix",
                "fieldLength": 3,
                "startPosition": 1117,
                "endPosition": 1119,
                "origination": "DMI Mail Record",
                "sortOrder": 101,
                "customHeaderField": null,
                "acxFieldName": "CEO_SUFFIX_NME",
                "appendFieldsId": 5561,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555423,
                "fieldName": "Chief Executive Officer - Prefix",
                "fieldLength": 10,
                "startPosition": 1120,
                "endPosition": 1129,
                "origination": "DMI Mail Record",
                "sortOrder": 102,
                "customHeaderField": null,
                "acxFieldName": "CEO_PREFIX_TITLE",
                "appendFieldsId": 5562,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555424,
                "fieldName": "Chief Executive Officer - Title",
                "fieldLength": 30,
                "startPosition": 1130,
                "endPosition": 1159,
                "origination": "DMI Mail Record",
                "sortOrder": 103,
                "customHeaderField": null,
                "acxFieldName": "CEO_TITLE_30",
                "appendFieldsId": 5563,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555425,
                "fieldName": "Chief Executive Officer - Management Responsibility Code (MRC)",
                "fieldLength": 4,
                "startPosition": 1160,
                "endPosition": 1163,
                "origination": "DMI Mail Record",
                "sortOrder": 104,
                "customHeaderField": null,
                "acxFieldName": "CEO_MRC",
                "appendFieldsId": 5564,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555426,
                "fieldName": "US 1987 SIC 1",
                "fieldLength": 8,
                "startPosition": 1164,
                "endPosition": 1171,
                "origination": "DMI Mail Record",
                "sortOrder": 105,
                "customHeaderField": null,
                "acxFieldName": "SIC_1_8",
                "appendFieldsId": 5565,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555427,
                "fieldName": "D&B Country Code",
                "fieldLength": 3,
                "startPosition": 1172,
                "endPosition": 1174,
                "origination": "DMI Mail Record",
                "sortOrder": 106,
                "customHeaderField": null,
                "acxFieldName": "NATIONAL_CD",
                "appendFieldsId": 5566,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555428,
                "fieldName": "D&B State Code",
                "fieldLength": 2,
                "startPosition": 1175,
                "endPosition": 1176,
                "origination": "DMI Mail Record",
                "sortOrder": 107,
                "customHeaderField": null,
                "acxFieldName": "DNB_STATE_CD",
                "appendFieldsId": 5567,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555429,
                "fieldName": "D&B US County Code",
                "fieldLength": 3,
                "startPosition": 1177,
                "endPosition": 1179,
                "origination": "DMI Mail Record",
                "sortOrder": 108,
                "customHeaderField": null,
                "acxFieldName": "COUNTY_CD",
                "appendFieldsId": 5568,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555430,
                "fieldName": "D&B US City Code",
                "fieldLength": 4,
                "startPosition": 1180,
                "endPosition": 1183,
                "origination": "DMI Mail Record",
                "sortOrder": 109,
                "customHeaderField": null,
                "acxFieldName": "DNB_CITY_CD",
                "appendFieldsId": 5569,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555431,
                "fieldName": "SMSA Code",
                "fieldLength": 3,
                "startPosition": 1184,
                "endPosition": 1186,
                "origination": "DMI Mail Record",
                "sortOrder": 110,
                "customHeaderField": null,
                "acxFieldName": "SMSA_CD",
                "appendFieldsId": 5570,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555432,
                "fieldName": "Filler",
                "fieldLength": 3,
                "startPosition": 1187,
                "endPosition": 1189,
                "origination": "DMI Mail Record",
                "sortOrder": 111,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 5571,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555433,
                "fieldName": "FIPS State Code",
                "fieldLength": 2,
                "startPosition": 1190,
                "endPosition": 1191,
                "origination": "DMI Mail Record",
                "sortOrder": 112,
                "customHeaderField": null,
                "acxFieldName": "FIPS_STATE_CD",
                "appendFieldsId": 5572,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555434,
                "fieldName": "FIPS County Code",
                "fieldLength": 3,
                "startPosition": 1192,
                "endPosition": 1194,
                "origination": "DMI Mail Record",
                "sortOrder": 113,
                "customHeaderField": null,
                "acxFieldName": "FIPS_COUNTY_CD",
                "appendFieldsId": 5573,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555435,
                "fieldName": "FIPS MSA Code",
                "fieldLength": 4,
                "startPosition": 1195,
                "endPosition": 1198,
                "origination": "DMI Mail Record",
                "sortOrder": 114,
                "customHeaderField": null,
                "acxFieldName": "FIPS_MSA_CD",
                "appendFieldsId": 5574,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555436,
                "fieldName": "Filler",
                "fieldLength": 3,
                "startPosition": 1199,
                "endPosition": 1201,
                "origination": "DMI Mail Record",
                "sortOrder": 115,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 5575,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555437,
                "fieldName": "Population Code",
                "fieldLength": 1,
                "startPosition": 1202,
                "endPosition": 1202,
                "origination": "DMI Mail Record",
                "sortOrder": 116,
                "customHeaderField": null,
                "acxFieldName": "POPULATION_CD",
                "appendFieldsId": 5576,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555438,
                "fieldName": "Filler",
                "fieldLength": 1,
                "startPosition": 1203,
                "endPosition": 1203,
                "origination": "DMI Mail Record",
                "sortOrder": 117,
                "customHeaderField": null,
                "acxFieldName": null,
                "appendFieldsId": 5577,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555439,
                "fieldName": "Chief Executive Officer Gender Code",
                "fieldLength": 9,
                "startPosition": 1204,
                "endPosition": 1212,
                "origination": "DMI Mail Record",
                "sortOrder": 118,
                "customHeaderField": null,
                "acxFieldName": "USA_GENDER_GOE_9",
                "appendFieldsId": 5578,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555440,
                "fieldName": "_D-U-N-S Number",
                "fieldLength": 9,
                "startPosition": 1213,
                "endPosition": 1221,
                "origination": "Franchise",
                "sortOrder": 119,
                "customHeaderField": null,
                "acxFieldName": "DUNS_FRANCHISE",
                "appendFieldsId": 5344,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555441,
                "fieldName": "Franchise Identifier Code",
                "fieldLength": 1,
                "startPosition": 1222,
                "endPosition": 1222,
                "origination": "Franchise",
                "sortOrder": 120,
                "customHeaderField": null,
                "acxFieldName": "FRAN_OPER_TYPE",
                "appendFieldsId": 5345,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555442,
                "fieldName": "Franchise Code 1",
                "fieldLength": 8,
                "startPosition": 1223,
                "endPosition": 1230,
                "origination": "Franchise",
                "sortOrder": 121,
                "customHeaderField": null,
                "acxFieldName": "FRAN_ID_1",
                "appendFieldsId": 5346,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555443,
                "fieldName": "Franchise 1 Description",
                "fieldLength": 45,
                "startPosition": 1231,
                "endPosition": 1275,
                "origination": "Franchise",
                "sortOrder": 122,
                "customHeaderField": null,
                "acxFieldName": "FRAN_1_DESC",
                "appendFieldsId": 5347,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555444,
                "fieldName": "Franchise Code 2",
                "fieldLength": 8,
                "startPosition": 1276,
                "endPosition": 1283,
                "origination": "Franchise",
                "sortOrder": 123,
                "customHeaderField": null,
                "acxFieldName": "FRAN_ID_2",
                "appendFieldsId": 5348,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555445,
                "fieldName": "Franchise 2 Description",
                "fieldLength": 45,
                "startPosition": 1284,
                "endPosition": 1328,
                "origination": "Franchise",
                "sortOrder": 124,
                "customHeaderField": null,
                "acxFieldName": "FRAN_2_DESC",
                "appendFieldsId": 5349,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555446,
                "fieldName": "Franchise Code 3",
                "fieldLength": 8,
                "startPosition": 1329,
                "endPosition": 1336,
                "origination": "Franchise",
                "sortOrder": 125,
                "customHeaderField": null,
                "acxFieldName": "FRAN_ID_3",
                "appendFieldsId": 5350,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555447,
                "fieldName": "Franchise 3 Description",
                "fieldLength": 45,
                "startPosition": 1337,
                "endPosition": 1381,
                "origination": "Franchise",
                "sortOrder": 126,
                "customHeaderField": null,
                "acxFieldName": "FRAN_3_DESC",
                "appendFieldsId": 5351,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555448,
                "fieldName": "Franchise Code 4",
                "fieldLength": 8,
                "startPosition": 1382,
                "endPosition": 1389,
                "origination": "Franchise",
                "sortOrder": 127,
                "customHeaderField": null,
                "acxFieldName": "FRAN_ID_4",
                "appendFieldsId": 5352,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555449,
                "fieldName": "Franchise 4 Description",
                "fieldLength": 45,
                "startPosition": 1390,
                "endPosition": 1434,
                "origination": "Franchise",
                "sortOrder": 128,
                "customHeaderField": null,
                "acxFieldName": "FRAN_4_DESC",
                "appendFieldsId": 5353,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555450,
                "fieldName": "Franchise Code 5",
                "fieldLength": 8,
                "startPosition": 1435,
                "endPosition": 1442,
                "origination": "Franchise",
                "sortOrder": 129,
                "customHeaderField": null,
                "acxFieldName": "FRAN_ID_5",
                "appendFieldsId": 5354,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555451,
                "fieldName": "Franchise 5 Description",
                "fieldLength": 45,
                "startPosition": 1443,
                "endPosition": 1487,
                "origination": "Franchise",
                "sortOrder": 130,
                "customHeaderField": null,
                "acxFieldName": "FRAN_5_DESC",
                "appendFieldsId": 5355,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555452,
                "fieldName": "Franchise Code 6",
                "fieldLength": 8,
                "startPosition": 1488,
                "endPosition": 1495,
                "origination": "Franchise",
                "sortOrder": 131,
                "customHeaderField": null,
                "acxFieldName": "FRAN_ID_6",
                "appendFieldsId": 5356,
                "hasFormatting": null,
                "formattingRule": null
            },
            {
                "outputLayoutFieldsId": 2555453,
                "fieldName": "Franchise 6 Description",
                "fieldLength": 45,
                "startPosition": 1496,
                "endPosition": 1540,
                "origination": "Franchise",
                "sortOrder": 132,
                "customHeaderField": null,
                "acxFieldName": "FRAN_6_DESC",
                "appendFieldsId": 5357,
                "hasFormatting": null,
                "formattingRule": null
            }
        ]
});
